# Generated by Django 2.1.7 on 2019-09-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_collaborative_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
